### ISSUE TITLE
No events found with description: 'ROYUAN .* System Control'

### ISSUE THREAD

**Issue by diedo42** [strodgers/epomaker-controller#48]
I follower the istruction, i used python3.12 -m venv epomaker  

epomakercontroller start-daemon               
Config file already exists at /home/xxxx/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
Device opened, initializing..
Failed to start daemon: read error

epomakercontroller start-daemon
Config file already exists at /home/xxxx/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
No events found with description: 'ROYUAN .* System Control'
Failed to start daemon: No device found

**Comment by strodgers** [comment]
Interesting, are you using an Epomaker RT100 keyboard or something else? Is it connected via USB cable?

can you please tell me the output of the following commands:
`cat /sys/class/input/event*/device/name`
and also:
`lsusb`


Thanks!

**Comment by diedo42** [comment]
┌──(diedo㉿diedo-bk)-[~]
└─$ cat /sys/class/input/event*/device/name
Lid Switch
Power Button
Power Button
AT Translated Set 2 keyboard
Generic USB Audio Consumer Control
Generic USB Audio
Telink Wireless Gaming Mouse
Telink Wireless Gaming Mouse Keyboard
Telink Wireless Gaming Mouse
Telink Wireless Gaming Mouse
HP HP USB-C Dock G5 System Control
Ideapad extra buttons
Elan Touchpad
Video Bus
HDA Intel PCH Mic
HDA Intel PCH Headphone
HDA Intel PCH HDMI/DP,pcm=3
HDA Intel PCH HDMI/DP,pcm=7
HDA Intel PCH HDMI/DP,pcm=8
RT100 BT5.0  Keyboard
RT100 BT5.0  Mouse
RT100 BT5.0



 ┌──(diedo㉿diedo-bk)-[~]
└─$ cat /etc/udev/rules.d/99-epomaker-rt100.rules
# Epomaker RT100 keyboard
SUBSYSTEM=="usb", ATTRS{idVendor}=="3151", ATTRS{idProduct}=="4010",
MODE="0666", GROUP="plugdev"


Thanks for the support

Il giorno ven 4 ott 2024 alle ore 16:18 strodgers ***@***.***>
ha scritto:

**Comment by diedo42** [comment]
$ epomakercontroller dev --udev
Config file already exists at /home/diedo/.epomaker-controller/config.json
Generating udev rule for the connected keyboard.
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
[
  {
    "path": "1-4.3.3:1.0",
    "vendor_id": "0x3151",
    "product_id": "0x4010",
    "serial_number": "",
    "release_number": 1287,
    "manufacturer_string": "ROYUAN",
    "product_string": "RT100 Wired",
    "usage_page": 0,
    "usage": 0,
    "interface_number": 0,
    "bus_type": 1
  },
  {
    "path": "1-4.3.3:1.1",
    "vendor_id": "0x3151",
    "product_id": "0x4010",
    "serial_number": "",
    "release_number": 1287,
    "manufacturer_string": "ROYUAN",
    "product_string": "RT100 Wired",
    "usage_page": 0,
    "usage": 0,
    "interface_number": 1,
    "bus_type": 1
  },
  {
    "path": "1-4.3.3:1.2",
    "vendor_id": "0x3151",
    "product_id": "0x4010",
    "serial_number": "",
    "release_number": 1287,
    "manufacturer_string": "ROYUAN",
    "product_string": "RT100 Wired",
    "usage_page": 0,
    "usage": 0,
    "interface_number": 2,
    "bus_type": 1
  }
]
Generating udev rule for Epomaker RT100 keyboard
Rule content:
# Epomaker RT100 keyboard
SUBSYSTEM=="usb", ATTRS{idVendor}=="3151", ATTRS{idProduct}=="4010", MODE="0666", GROUP="plugdev"


Rule file path: /etc/udev/rules.d/99-epomaker-rt100.rules
Please enter your password if prompted
[sudo] password for diedo:             
Rule generated successfully
                                                                                


$ epomakercontroller list-temp-devices 
Config file already exists at /home/diedo/.epomaker-controller/config.json

Temperature key: nvme
  Label: Composite
  Current: 44.85°C
  High: 83.85°C
  Critical: 84.85°C
  Label: Sensor 1
  Current: 44.85°C
  High: 65261.85°C
  Critical: 65261.85°C
  Label: Sensor 2
  Current: 41.85°C
  High: 65261.85°C
  Critical: 65261.85°C

Temperature key: pch_cannonlake
  Label: N/A
  Current: 37.0°C
  High: N/A°C
  Critical: N/A°C

Temperature key: iwlwifi_1
  Label: N/A
  Current: 34.0°C
  High: N/A°C
  Critical: N/A°C

Temperature key: coretemp
  Label: Package id 0
  Current: 44.0°C
  High: 100.0°C
  Critical: 100.0°C
  Label: Core 0
  Current: 43.0°C
  High: 100.0°C
  Critical: 100.0°C
  Label: Core 1
  Current: 44.0°C
  High: 100.0°C
  Critical: 100.0°C
                                                                                
$ epomakercontroller start-daemon
Config file already exists at /home/diedo/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
Device opened, initializing..
Failed to start daemon: read error
                                                                                
$ epomakercontroller start-daemon
Config file already exists at /home/diedo/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
No events found with description: 'ROYUAN .* System Control'
Failed to start daemon: No device found

**Comment by strodgers** [comment]
@diedo42 thanks for the info, I take it you are connecting to the keyboard via bluetooth? At the moment, only wired USB connection is supported. You have to use a USB C cable and make sure the keyboard is switched to 'Off' (otherwise it just charges but remains on BT/wireless mode)

**Comment by diedo42** [comment]
@strodgers 
I'm sure i used wired connection with power button on off and OS on WIN and is connected via usbC cable

and this is the output 

$ cat /sys/class/input/event*/device/name
Lid Switch
Power Button
Power Button
AT Translated Set 2 keyboard
Generic USB Audio Consumer Control
Generic USB Audio
Telink Wireless Gaming Mouse
Telink Wireless Gaming Mouse Keyboard
Telink Wireless Gaming Mouse
Telink Wireless Gaming Mouse
HP HP USB-C Dock G5 System Control
Ideapad extra buttons
Elan Touchpad
Video Bus
HDA Intel PCH Mic
HDA Intel PCH Headphone
HDA Intel PCH HDMI/DP,pcm=3
HDA Intel PCH HDMI/DP,pcm=7
HDA Intel PCH HDMI/DP,pcm=8
ROYUAN RT100 Wired
                                                                                
$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 03f0:036b HP, Inc HP USB-C Dock G5
Bus 001 Device 003: ID 04f3:0c4b Elan Microelectronics Corp. ELAN:Fingerprint
Bus 001 Device 004: ID 03f0:056b HP, Inc USB Audio
Bus 001 Device 005: ID 04ca:7070 Lite-On Technology Corp. Integrated Camera
Bus 001 Device 006: ID 03f0:086b HP, Inc USB2734
Bus 001 Device 007: ID 320f:221d Telink Wireless Gaming Mouse
Bus 001 Device 008: ID 03f0:046b HP, Inc HP USB-C Dock G5
Bus 001 Device 009: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 010: ID 214b:7250 Huasheng Electronics USB2.0 HUB
Bus 001 Device 011: ID 214b:7250 Huasheng Electronics USB2.0 HUB
Bus 001 Device 012: ID 3151:4010 ROYUAN RT100 Wired
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 002: ID 03f0:066b HP, Inc HP USB-C Dock G5
Bus 002 Device 003: ID 03f0:076b HP, Inc USB5734
Bus 002 Device 004: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter

**Comment by diedo42** [comment]
i also tried to change .epomaker-controller/config.json   with Wired instead of System Control, now it found the device but have an other error

  GNU nano 7.2      /home/diedo/.epomaker-controller/config.json                
{
    "VENDOR_ID": 12625,
    "PRODUCT_IDS_WIRED": [
        16400,
        16405
    ],
    "PRODUCT_IDS_24G": [
        16401,
        16406
    ],
    "USE_WIRELESS": false,
    "DEVICE_DESCRIPTION_REGEX": "ROYUAN .* Wired",
    "CONF_LAYOUT_PATH": "EpomakerRT100-UK-ISO.json",
    "CONF_KEYMAP_PATH": "EpomakerRT100.json"
}

epomakercontroller start-daemon                  
Config file already exists at /home/diedo/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
Device opened, initializing..
Failed to start daemon: read error

**Comment by diedo42** [comment]
I found that in the config layout i see EpomakerRT100-UK-ISO.json

But i'm sure i bought the US version

**Comment by diedo42** [comment]
@strodgers any news about it?

**Comment by strodgers** [comment]
hey @diedo42 sorry for the late reply!

I have made a reasonable amount of changes since version 0.0.6 so need to do a new release, which I will do now. Might be some changes in there that help with your problem.

I have seen when I test the controller sometimes that the System Control interface doesn't show for some reason, but usually if I unplug and plug back in it shows again. The reason for using the one with System Control in the name (rather than just ' ROYUAN RT100 Wired') is that using that interface doesn't seem to interfere with usual keyboard usage. Otherwise, the keyboard is basically unresponsive to typing etc when the controller is doing something like sending an update to the screen.

I had a long troubleshooting adventure with another user who eventually happened to upgrade the keyboard firmware using the official windows driver software and the problems went away. What you're describing doesn't sound like the same problem, but could be worth trying first.

As for the config layout, it _shouldn't_ result in a complete lack of communication with the keyboard, it would just mess up keymappings if you tried to do that. Things like sending temp/time/cpu usage should work.

I'll reply again when I do the release for 0.0.7

Thanks for your patience!

**Comment by diedo42** [comment]
@strodgers i missed your edit btw if i plug in the keyboard i see 5 event with the name ROYUAN but after i run the tool epomakercontroller and run again evtest, then i see only 1 event named ROYUAN RT100 Wired

$ sudo evtest                             
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event10:	Video Bus
/dev/input/event11:	HDA Intel PCH Mic
/dev/input/event12:	HDA Intel PCH Headphone
/dev/input/event13:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event14:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event15:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event16:	Generic USB Audio Consumer Control
/dev/input/event17:	Generic USB Audio
/dev/input/event18:	HP HP USB-C Dock G5 System Control
/dev/input/event19:	ROYUAN RT100 Wired
/dev/input/event2:	Power Button
/dev/input/event20:	ROYUAN RT100 Wired Consumer Control
/dev/input/event21:	ROYUAN RT100 Wired System Control
/dev/input/event22:	ROYUAN RT100 Wired Keyboard
/dev/input/event23:	ROYUAN RT100 Wired Mouse
/dev/input/event24:	ROYUAN RT100 Wired
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	Telink Wireless Gaming Mouse
/dev/input/event5:	Telink Wireless Gaming Mouse Keyboard
/dev/input/event6:	Telink Wireless Gaming Mouse
/dev/input/event7:	Telink Wireless Gaming Mouse
/dev/input/event8:	Ideapad extra buttons
/dev/input/event9:	Elan Touchpad
Select the device event number [0-24]: ^C
                                                                                
$ epomakercontroller start-daemon coretemp
Config file already exists at /home/diedo/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
Device opened, initializing..
Failed to start daemon: read error
                                                                                
$ sudo evtest                             
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Power Button
/dev/input/event10:	Video Bus
/dev/input/event11:	HDA Intel PCH Mic
/dev/input/event12:	HDA Intel PCH Headphone
/dev/input/event13:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event14:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event15:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event16:	Generic USB Audio Consumer Control
/dev/input/event17:	Generic USB Audio
/dev/input/event18:	HP HP USB-C Dock G5 System Control
/dev/input/event19:	ROYUAN RT100 Wired
/dev/input/event2:	Power Button
/dev/input/event3:	AT Translated Set 2 keyboard
/dev/input/event4:	Telink Wireless Gaming Mouse
/dev/input/event5:	Telink Wireless Gaming Mouse Keyboard
/dev/input/event6:	Telink Wireless Gaming Mouse
/dev/input/event7:	Telink Wireless Gaming Mouse
/dev/input/event8:	Ideapad extra buttons
/dev/input/event9:	Elan Touchpad
Select the device event number [0-19]: ^C

**Comment by strodgers** [comment]
Collating this into https://github.com/strodgers/epomaker-controller/issues/53
