### ISSUE TITLE
Issue with Desktop PC, working on laptop

### ISSUE THREAD

**Issue by mdvries** [strodgers/epomaker-controller#51]
I have an issue with getting the controller to display information. Setting up UDEV ruules goes fine, the config.json looks good. However when I do

epomakercontroller start-daemon

I get this error

Config file already exists at /home/martin/.epomaker-controller/config.json
WARNING: If this program errors out or you cancel early, the keyboard
              may become unresponsive. It should work fine again if you unplug and plug
               it back in!
Device opened, initializing..
Failed to start daemon: read error
---
When I then run the same command again I get this error:

Could not find Wired interface
Failed to start daemon: No device found
---

I then have to unplug and plug the cable to reproduce it again. I keep getting the read error.

What does this mean? How can I fix this?

On my laptop I got it working fine. I amrunning on both this desktop PC and the latop Ubuntu 24.10.

**Comment by mdvries** [comment]
Some additional information I found in the syslog:

2024-11-27T00:54:39.793421+01:00 mars acpid: input device has been disconnected, fd 32
2024-11-27T00:54:39.806745+01:00 mars acpid: input device has been disconnected, fd 33
2024-11-27T00:54:39.822717+01:00 mars acpid: input device has been disconnected, fd 34
2024-11-27T00:54:39.877542+01:00 mars kernel: hid-generic 0003:3151:4010.0064: unknown main item tag 0x0
2024-11-27T00:54:39.877556+01:00 mars kernel: message repeated 5 times: [ hid-generic 0003:3151:4010.0064: unknown main item tag 0x0]
2024-11-27T00:54:39.877556+01:00 mars kernel: hid-generic 0003:3151:4010.0064: collection stack underflow
2024-11-27T00:54:39.877559+01:00 mars kernel: hid-generic 0003:3151:4010.0064: item 0 0 0 12 parsing failed
2024-11-27T00:54:39.877560+01:00 mars kernel: hid-generic: probe of 0003:3151:4010.0064 failed with error -22

**Comment by mdvries** [comment]
And this is dmesg output when initially connecting the keyboard and after that run the command.

[INSERTING USB CABLE]
[ 3359.248454] usb 1-10.3: new full-speed USB device number 66 using xhci_hcd
[ 3359.327434] usb 1-10.3: New USB device found, idVendor=3151, idProduct=4010, bcdDevice= 5.00
[ 3359.327437] usb 1-10.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[ 3359.327439] usb 1-10.3: Product: RT100 Wired
[ 3359.327440] usb 1-10.3: Manufacturer: ROYUAN
[ 3359.335751] input: ROYUAN RT100 Wired as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10.3/1-10.3:1.0/0003:3151:4010.0069/input/input211
[ 3359.387866] hid-generic 0003:3151:4010.0069: input,hidraw9: USB HID v1.11 Keyboard [ROYUAN RT100 Wired] on usb-0000:00:14.0-10.3/input0
[ 3359.388781] input: ROYUAN RT100 Wired Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10.3/1-10.3:1.1/0003:3151:4010.006A/input/input212
[ 3359.440963] input: ROYUAN RT100 Wired System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10.3/1-10.3:1.1/0003:3151:4010.006A/input/input213
[ 3359.441053] input: ROYUAN RT100 Wired Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10.3/1-10.3:1.1/0003:3151:4010.006A/input/input214
[ 3359.441126] input: ROYUAN RT100 Wired Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10.3/1-10.3:1.1/0003:3151:4010.006A/input/input215
[ 3359.441189] input: ROYUAN RT100 Wired as /devices/pci0000:00/0000:00:14.0/usb1/1-10/1-10.3/1-10.3:1.1/0003:3151:4010.006A/input/input216
[ 3359.441271] hid-generic 0003:3151:4010.006A: input,hiddev5,hidraw10: USB HID v1.11 Keyboard [ROYUAN RT100 Wired] on usb-0000:00:14.0-10.3/input1
[ 3359.441729] hid-generic 0003:3151:4010.006B: hiddev7,hidraw13: USB HID v1.11 Device [ROYUAN RT100 Wired] on usb-0000:00:14.0-10.3/input2

[AFTER RUNNING COMMAND]
[ 3364.535053] hid-generic 0003:3151:4010.006C: unknown main item tag 0x0
[ 3364.535059] hid-generic 0003:3151:4010.006C: unknown main item tag 0x0
[ 3364.535063] hid-generic 0003:3151:4010.006C: unknown main item tag 0x0
[ 3364.535067] hid-generic 0003:3151:4010.006C: unknown main item tag 0x0
[ 3364.535071] hid-generic 0003:3151:4010.006C: unknown main item tag 0x0
[ 3364.535109] hid-generic 0003:3151:4010.006C: collection stack underflow
[ 3364.535114] hid-generic 0003:3151:4010.006C: item 0 0 0 12 parsing failed
[ 3364.535120] hid-generic: probe of 0003:3151:4010.006C failed with error -22

**Comment by strodgers** [comment]
Collating this into https://github.com/strodgers/epomaker-controller/issues/53
